main : main.cc epsilon.cc addition.cc compare.cc
	g++ -o epsilon main.cc epsilon.cc addition.cc compare.cc

main.cc : epsilon.cc addition.cc compare.cc
	g++ -o epsilon main.cc epsilon.cc addition.cc compare.cc
